services:
  postgres:
    image: postgres:15
    container_name: postgres_db_medical
    environment:
      POSTGRES_DB:  medical_facility_information_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ppp
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

